### ISSUE TITLE
Unable to resolve name [org.apache.ignite.cache.hibernate.HibernateRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]

### ISSUE THREAD

**Issue by pavankjadda** [pierre-filliolaud/jhipster-ignite-app#2]
I downloaded your repository and created new projects jhipster app. When I tried to run I got following error `Unable to resolve name [org.apache.ignite.cache.hibernate.HibernateRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]`. Code uploaded to [github](https://github.com/pavankjadda/ApacheIgnite-JHipster-Docker). I am not sure why I got this.

Error:

```
ignitejhipster-app_1         | 2018-02-20 15:41:58.227  WARN 6 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
ignitejhipster-app_1         | 2018-02-20 15:41:58.229  INFO 6 --- [           main] com.hazelcast.core.LifecycleService      : [172.18.0.2]:5701 [dev] [3.6.5] Address[172.18.0.2]:5701 is SHUTTING_DOWN
ignitejhipster-app_1         | 2018-02-20 15:41:58.232  INFO 6 --- [           main] com.hazelcast.instance.Node              : [172.18.0.2]:5701 [dev] [3.6.5] Shutting down multicast service...
ignitejhipster-app_1         | 2018-02-20 15:41:58.244  INFO 6 --- [           main] com.hazelcast.instance.Node              : [172.18.0.2]:5701 [dev] [3.6.5] Shutting down connection manager...
ignitejhipster-app_1         | 2018-02-20 15:41:58.248  INFO 6 --- [           main] com.hazelcast.instance.Node              : [172.18.0.2]:5701 [dev] [3.6.5] Shutting down node engine...
ignitejhipster-app_1         | 2018-02-20 15:41:58.270  INFO 6 --- [           main] com.hazelcast.instance.NodeExtension     : [172.18.0.2]:5701 [dev] [3.6.5] Destroying node NodeExtension.
ignitejhipster-app_1         | 2018-02-20 15:41:58.271  INFO 6 --- [           main] com.hazelcast.instance.Node              : [172.18.0.2]:5701 [dev] [3.6.5] Hazelcast Shutdown is completed in 39 ms.
ignitejhipster-app_1         | 2018-02-20 15:41:58.272  INFO 6 --- [           main] com.hazelcast.core.LifecycleService      : [172.18.0.2]:5701 [dev] [3.6.5] Address[172.18.0.2]:5701 is SHUTDOWN
ignitejhipster-app_1         | 2018-02-20 15:41:58.272  INFO 6 --- [           main] c.m.myapp.config.CacheConfiguration      : Closing Cache Manager
ignitejhipster-app_1         | 2018-02-20 15:41:58.321  WARN 6 --- [           main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.RuntimeException: Could not postProcess org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@ae7950d of type class org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler)
ignitejhipster-app_1         | 2018-02-20 15:41:58.329 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application startup failed
ignitejhipster-app_1         | 
ignitejhipster-app_1         | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
ignitejhipster-app_1         | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
ignitejhipster-app_1         | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851)
ignitejhipster-app_1         | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
ignitejhipster-app_1         | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
ignitejhipster-app_1         | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
ignitejhipster-app_1         | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
ignitejhipster-app_1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
ignitejhipster-app_1         | 	at com.mycompany.myapp.IgnitejhipsterApp.main(IgnitejhipsterApp.java:64)
ignitejhipster-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ignitejhipster-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ignitejhipster-app_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ignitejhipster-app_1         | 	at java.lang.reflect.Method.invoke(Method.java:498)
ignitejhipster-app_1         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
ignitejhipster-app_1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
ignitejhipster-app_1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
ignitejhipster-app_1         | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
ignitejhipster-app_1         | Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
ignitejhipster-app_1         | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:261)
ignitejhipster-app_1         | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:225)
ignitejhipster-app_1         | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
ignitejhipster-app_1         | 	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:295)
ignitejhipster-app_1         | 	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2444)
ignitejhipster-app_1         | 	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2440)
ignitejhipster-app_1         | 	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1857)
ignitejhipster-app_1         | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
ignitejhipster-app_1         | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
ignitejhipster-app_1         | 	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
ignitejhipster-app_1         | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
ignitejhipster-app_1         | 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
ignitejhipster-app_1         | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
ignitejhipster-app_1         | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:373)
ignitejhipster-app_1         | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:362)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
ignitejhipster-app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
ignitejhipster-app_1         | 	... 22 common frames omitted
ignitejhipster-app_1         | Caused by: org.hibernate.HibernateException: could not instantiate RegionFactory [org.apache.ignite.cache.hibernate.HibernateRegionFactory]
ignitejhipster-app_1         | 	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:101)
ignitejhipster-app_1         | 	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:46)
ignitejhipster-app_1         | 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:105)
ignitejhipster-app_1         | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:251)
ignitejhipster-app_1         | 	... 38 common frames omitted
ignitejhipster-app_1         | Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.apache.ignite.cache.hibernate.HibernateRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]
ignitejhipster-app_1         | 	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:128)
ignitejhipster-app_1         | 	at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:87)
ignitejhipster-app_1         | 	... 41 common frames omitted
```

**Comment by pavankjadda** [comment]
Refer project https://github.com/pavankjadda/ApacheIgnite-JHipster-Docker
